# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: IAC

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Create Redshift Cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get IP
        run: ip=$(curl -s https://api.ipify.org)
      - name: Set Database Password
        run: dbpass=${{ secrets.DB_PASS }}
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-2"
      - name: Terraform Plan
        run: terraform plan -var-file="dev.tfvars" -var ip="$ip" -var rs_master_pass="$dbpass"

#  build:
#    name: Build Java Code
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 11
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'adopt'
#      - name: Build with Maven
#        run: mvn -B package --file pom.xml
#        env:
#          aws_key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
#  destroy:
#    name: Destroy Redshift Cluster
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Configure AWS credentials from Test account
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      - name: Terraform Destroy
#        run: terraform destroy
